baseURL = 'https://mmontesanonyc.github.io/Makino-Guitars-website/'
languageCode = 'en-us'
title = 'Makino Guitars'
theme = 'hugo-bootstrap'
navbarBgColorClass = 'secondary'


[[menu.main]]
    name = "Instagram"
    pre = "<i class='fab fa-instagram'></i>"
    weight = -10
    identifier = "guitars"
    url = "https://www.instagram.com/takmakino"

[[menu.main]]
    name = "Contact"
    pre = "<i class='fas fa-envelope-square'></i>"
    weight = 10
    identifier = "contact"
    url = "mailto:tak@makinoguitars.com"

    