baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Makino Guitars'
theme = 'hugo-bootstrap'
navbarBgColorClass = 'secondary'


[[menu.main]]
    name = "About"
    pre = "<i class='fa-solid fa-circle-info'></i>"
    weight = -90
    identifier = "about"
    url = "/about"

[[menu.main]]
    name = "Guitars"
    pre = "<i class='fas fa-guitar'></i>"
    weight = -10
    identifier = "guitars"
    url = "/guitars"

[[menu.main]]
    name = "Contact"
    pre = "<i class='fas fa-envelope-square'></i>"
    weight = 10
    identifier = "contact"
    url = "/contact"

    