baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Makino Guitars'
theme = 'hugo-bootstrap'
navbarBgColorClass = 'secondary'


[[menu.main]]
    name = "About"
    pre = ""
    weight = 10
    identifier = "about"
    url = "/about"

[[menu.main]]
    name = "Guitars"
    pre = ""
    weight = -10
    identifier = "guitars"
    url = "/guitars"



[[menu.footer]]
    name = "Instagram"
    pre = "<i class='fab fa-instagram'></i>"
    weight = -10
    identifier = "guitars"
    url = "https://www.instagram.com/takmakino"

[[menu.footer]]
    name = "Contact"
    pre = "<i class='fas fa-envelope-square'></i>"
    weight = 10
    identifier = "contact"
    url = "/contact"